<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Close</name>
   <tag></tag>
   <elementGuidId>9315079e-1c57-43b4-856f-a59365ce185f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#closeLargeModal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='closeLargeModal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2789a012-6b73-42de-ac3e-3d2cbdfb0e21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>closeLargeModal</value>
      <webElementGuid>a2defec1-8a52-47fc-ab97-414ec1978256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6785c76d-dd64-4e4b-bbe6-bd79c2cade29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>83366a55-b53b-4e1f-887b-a188fd691f76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>a90897f2-1ac2-466f-8416-f0e5846a3199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;closeLargeModal&quot;)</value>
      <webElementGuid>803eaa33-d504-4aa4-8d9b-3d754b7362bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='closeLargeModal']</value>
      <webElementGuid>40e4c1cd-b441-4f9a-ad33-b4a5e6c81270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NCR Delhi'])[1]/following::button[1]</value>
      <webElementGuid>1a215d34-5091-4375-bfd8-f98d252050a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State and City'])[2]/following::button[1]</value>
      <webElementGuid>8056122f-d026-4fdc-b32c-52f0f1fddfc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Close']/parent::*</value>
      <webElementGuid>16e8a934-c9c6-4d3f-a63a-3d47d835db6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>30aca734-dcdb-43df-926b-6c4b53ed3a2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'closeLargeModal' and @type = 'button' and (text() = 'Close' or . = 'Close')]</value>
      <webElementGuid>60e4c76e-7517-4da6-b4b6-dfec9c065f2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
