<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select City</name>
   <tag></tag>
   <elementGuidId>e5e0d8c1-e1b7-4c0e-8798-2c328c33d73f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='stateCity-wrapper']/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a8b91253-83a3-4a24-a79e-2f169e43b7e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-4 col-sm-12</value>
      <webElementGuid>5d4aaa5e-105a-465f-a647-e77475af14fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select City</value>
      <webElementGuid>449f3d49-a892-44a5-a7a6-20c35604a669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stateCity-wrapper&quot;)/div[@class=&quot;col-md-4 col-sm-12&quot;]</value>
      <webElementGuid>4671e3ff-8808-4bc1-be3c-cfd6f6fdf920</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='stateCity-wrapper']/div[3]</value>
      <webElementGuid>c3b87a96-0580-4cac-bf85-a5fd7aa30493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select State'])[1]/following::div[6]</value>
      <webElementGuid>60d2c8b9-e05f-48bd-81a0-4d167da0d454</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State and City'])[1]/following::div[11]</value>
      <webElementGuid>d2cb2e6e-543e-4290-bb65-101146992e70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::div[10]</value>
      <webElementGuid>0e0a3f1b-0e95-4bd5-a462-712173cb96c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[3]</value>
      <webElementGuid>38fc4584-3afc-4735-8526-eb83af9b81ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Select City' or . = 'Select City')]</value>
      <webElementGuid>de4bb5e2-4316-4bd4-9cc8-c678f089a320</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
