<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_Regist</name>
   <tag></tag>
   <elementGuidId>2183030c-4e87-4d5c-b611-6e0ae694c24b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#userForm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='userForm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>0d211969-7f97-41f1-a7ce-3f3c28777527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>userForm</value>
      <webElementGuid>f8baf759-5673-460a-999a-13a8f2f3d00d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>was-validated</value>
      <webElementGuid>ec41e8bc-0133-43f8-ac43-4723453fc250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NameEmailGenderMaleFemaleOtherMobile(10 Digits)Date of BirthSubjects HobbiesSportsReadingMusicPictureSelect pictureCurrent AddressState and CitySelect StateSelect CitySubmit</value>
      <webElementGuid>be33607c-0dde-42ea-9f1d-9f2c8e40366b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userForm&quot;)</value>
      <webElementGuid>57eff2df-b336-4124-b93f-b1eeca613c50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//form[@id='userForm']</value>
      <webElementGuid>a065f164-03c0-4263-ab6c-f638dd7ad150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div[2]/div[2]/form</value>
      <webElementGuid>0de29da9-9b5d-4500-865b-39351d93978d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Student Registration Form'])[1]/following::form[1]</value>
      <webElementGuid>93ca2060-8018-412f-97da-6630b62ec08c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Practice Form'])[2]/following::form[1]</value>
      <webElementGuid>385d0596-12ed-4209-ae20-679b5791d3a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>54aa1190-6076-4844-8a60-a16c3df951f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[@id = 'userForm' and (text() = 'NameEmailGenderMaleFemaleOtherMobile(10 Digits)Date of BirthSubjects HobbiesSportsReadingMusicPictureSelect pictureCurrent AddressState and CitySelect StateSelect CitySubmit' or . = 'NameEmailGenderMaleFemaleOtherMobile(10 Digits)Date of BirthSubjects HobbiesSportsReadingMusicPictureSelect pictureCurrent AddressState and CitySelect StateSelect CitySubmit')]</value>
      <webElementGuid>b18d1724-7680-4729-a358-37838942fab0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
